

# This file was *autogenerated* from the file UTnUtil.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)############################# Functions ######################################

#Gets the unipotent upertriangular nxn matrices over the field f
def getUTn(n: int, f: sage.rings.finite_rings.finite_field_prime_modn):
    toRet = []
    fillings = getListOfLength(((n-_sage_const_1 )*n)/_sage_const_2 , f)

    for filling in fillings:
        toRet.append(getUTnMatFromList(n, f, filling))
    return toRet

def getUTnMatFromList(n: int, f: sage.rings.finite_rings.finite_field_prime_modn, l: list):
    #((n-1)*n)/2 is the number of entries above the diagonal
    if len(l) != ((n-_sage_const_1 )*n)/_sage_const_2 :
        raise NameError('Invalid array length')
    
    mat = copy(MatrixSpace(f,n,n).identity_matrix())
    current = _sage_const_0 
    for i in range(n):
        for j in range(n-i-_sage_const_1 ):
            mat[i,j+i+_sage_const_1 ] = l[current]
            current += _sage_const_1 
    return mat

#Recursivley generates all lists of length n composed of element of f
#Returns a list of all such lists
def getListOfLength(n: int, f: sage.rings.finite_rings.finite_field_prime_modn):
    toRet = []
    if n == _sage_const_1 :
        for elem in f:
            toRet.append([elem])
        return toRet
    
    for elem in f:
        beginnings = getListOfLength(n-_sage_const_1 ,f)
        for beginning in beginnings:
            beginning.append(elem)
            toRet.append(beginning)
    return toRet

#Remember, python uses 0 indexed lists, so we have to offset our entries by 1
def blackout(mat: sage.matrix, entries: list):
    for entry in entries:
        mat[entry[_sage_const_0 ],entry[_sage_const_1 ]] = _sage_const_0 
    return mat

def getConjClasses(toSearch, n,f):
    found = []
    classes = []
    conjugators = getUTn(n,f)
    for mat in toSearch:
        if mat not in found:
            found.append(mat)
            conjClass = [mat]
            for c in conjugators:
                current = c*mat*c.inverse()
                if current not in conjClass:
                    found.append(current)
                    conjClass.append(current)
            classes.append(conjClass)
    return classes

def blackoutForBottomLeft(mat: sage.matrix, n: int):
    toBlackout = []
    for i in range(n):
        for j in range(n):
            if j >= i:
                toBlackout.append([i,j])
    return blackout(mat, toBlackout)

def fillMatFromList(toFill: list, entries: list, n: int, f: sage.rings.finite_rings.finite_field_prime_modn):
    if len(toFill) != len(entries):
        raise NameError('Inputs must have the same length')

    mat = MatrixSpace(f,n,n).identity_matrix() - MatrixSpace(f,n,n).identity_matrix()
    for i in range(len(entries)):
        e = toFill[i]
        mat[e[_sage_const_0 ],e[_sage_const_1 ]] = entries[i]

    return mat

def getMatsOfShape(shape: list, n: int, f: sage.rings.finite_rings.finite_field_prime_modn):
    toRet = []
    fillings = getListOfLength(len(shape),f)
    for filling in fillings:
        toRet.append(fillMatFromList(shape, filling, n, f))
    return toRet

def printClasses(classes):
    for c in classes:
        print("Size: " + str(len(c)))
        for e in c:
            print(e)
            print("------")
        print("######")
    print("Number of classes: " + str(len(classes)))


